name: Python application
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ‘3.x’
    - name: Install dependencies
      run: |
        pip install pipenv pytest
    - name: Run tests
      run: |
        pipenv run pytest
